-- 1) SQL_VARIANT_PROPERTY 

SELECT 10 AS 'Número'
SELECT 45.50 AS 'Decimal'
SELECT 'Marcus' AS 'Nome'
SELECT '20/06/2021' AS 'Data'

SELECT SQL_VARIANT_PROPERTY(10,'BaseType')
SELECT SQL_VARIANT_PROPERTY(45.50,'BaseType')
SELECT SQL_VARIANT_PROPERTY('Marcus','BaseType')
SELECT SQL_VARIANT_PROPERTY('20/06/2021','BaseType')